### ISSUE TITLE
How to encrypt message with the symetric key of kem

### ISSUE THREAD

**Issue by VegeBun-csj** [open-quantum-safe/liboqs-rust#176]
How to encrypt message with the symetric key of kem when i generated a shared secret? 
eg: https://github.com/open-quantum-safe/liboqs-rust/blob/main/oqs/src/lib.rs#L31, how can i use `b_kem_ss` to encrypt message?

**Comment by thomwiggers** [comment]
This crate offers only public-key cryptography primitives (specifically for key exchange and digital signatures): you seem to be looking for symmetric key encryption. You could for example look at one of the Rust-Crypto crates, such as https://docs.rs/aes-gcm/latest/aes_gcm/.

On a related note, a brief warning: if you're playing with cryptography, for fun or to learn stuff: cool! By all means, go for it and have fun. Just maybe add some warnings in the README and other docs that it's just an experiment and not meant for production use. "Rolling your own crypto" is completely fine, if it's for fun and learning. 😄 

But if you're trying to build something that is actually going to be published and/or used: cryptography can be very, very tricky and nuanced, and tiny mistakes can be very painful. Going for something off-the-shelf is usually safer. Otherwise, you need to get some expert help.
